config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :restaurants do
    resources :reviews, only: [:new, :create]
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = [ "chinese", "italian", "japanese", "french", "belgian" ]

  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, presence: true
  validates :rating, inclusion: { in: 0..5 }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurant = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant), notice: "Restaurant was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def review
    @restaurant = Restaurant.find(params[:id])
    @review_content = @restaurant.review_content
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<div class="container">
  <h1>Restaurants</h1>
    <div class="container">
      <% @restaurant.each do |restaurant| %>
      <%= link_to restaurant_path(restaurant) do %>
      <p><%= restaurant.name %></p>
      <% end %>
      <p><%= restaurant.address %></p>
      <p><%= restaurant.phone_number %></p>
      <p><%= restaurant.category %></p>
      <% end %>
    </div>
</div>

app/views/restaurants/new.html.erb
<div class="container">
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :phone_number %>
  <%= f.input :category, collection: Restaurant::CATEGORIES, selected: Restaurant::CATEGORIES[-2] %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <h1>Restaurant</h1>
      <p><%= @restaurant.name %></p>
      <p><%= @restaurant.address %></p>
      <p><%= @restaurant.phone_number %></p>
      <p><%= @restaurant.category %></p>
</div>

<div>
  <h1>Reviews</h1>
  <% @restaurant.reviews.each do |review| %>
  <p><%= review.rating %></p>
  <p><%= review.content %></p>
  <% end %>
  <%= link_to "Leave a review", new_restaurant_review_path(@restaurant) %>
</div>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>